### ISSUE TITLE
E2E Test for Offline DB Access

### ISSUE THREAD

**Issue by naveensrinivasan** [defenseunicorns/uds-security-hub-v1-archive#123]
### Description:
With the integration of [Offline DB access in PR #119](https://github.com/defenseunicorns/uds-security-hub/pull/119), we need to implement end-to-end (E2E) tests to ensure its functionality.

### Background:
Currently, we lack an automated E2E test for offline DB access. Testing requires an initialized folder containing `trivy.db`. More details can be found in [Issue #486](https://github.com/aquasecurity/trivy/issues/486) on the Trivy repository.

### Steps to Reproduce:
1. **Initialize Offline DB:**
   ```sh
   go run main.go -p ./pkg/scan/testdata/zarf-package-mattermost-arm64-9.9.1-uds.0.tar.zst -d /var/folders/pf/bq3t19j505xg4pprmb3ls7r0000gn/T/trivy-db-2535363142/db
   ```

2. **Offline DB Directory Structure:**
   The directory for the offline DB should be structured as follows:
   ```sh
   tree /var/folders/pf/bq3t19j505xg4pprmb3ls7r0000gn/T/trivy-db-2535363142/db
   ├── db
   │   ├── metadata.json
   │   ├── trivy.db
   │   └── fanal.db
   ```

### Tasks:
- [ ] Create a folder containing all necessary data (approximately 500 MB).
- [ ] Host the folder in a cloud provider.
- [ ] Update the tests to download this folder during GitHub Actions.
- [ ] Ensure the tests pass successfully.

### Notes:
- Ensure that the offline DB contains the following files:
  - `metadata.json`
  - `trivy.db`
  - `fanal.db`

### References:
- [PR #119: Offline DB access](https://github.com/defenseunicorns/uds-security-hub/pull/119)
- [Trivy Issue #486](https://github.com/aquasecurity/trivy/issues/486)

**Comment by partkyle** [comment]
related #225
