### ISSUE TITLE
Provide Zarf Team with differences between rootfs and SBOM scanner

### ISSUE THREAD

**Issue by partkyle** [defenseunicorns/uds-security-hub-v1-archive#309]
Ultimately, uds-security-hub should be scanning using the SBOMs from the package. Since we have noticed differences between these two scanners, we should provide this information to the zarf team so that they can evaluate if the generated SBOMs are sufficient.

Use some images from `scripts/names.txt` as examples.

```[tasklist]
### Tasks
- [ ] Scan packages using rootfs and collect results
- [ ] Scan packages using sbom and collect results
- [ ] for packages that have different results collect them for the zarf team
- [ ] create an issue on the zarf project
```
