### ISSUE TITLE
Remove Looker Dashboard

### ISSUE THREAD

**Issue by adam-defenseunicorns** [defenseunicorns/uds-security-hub-v1-archive#312]
Remove Looker in favor of Metabase 
```[tasklist]
### Tasks
- [ ] Post announcement in Security Hub
- [ ] Remove Looker Dashboard
- [ ] Clean up/ Remove related code
```

**Comment by naveensrinivasan** [comment]
@adam-defenseunicorns, as we discussed in our meeting, the clean-up of `looker`- related code will happen after we have final design approval of the work we are doing now. We want to be careful about removing things. 

We can remove the dashboard.

**Comment by naveensrinivasan** [comment]
https://github.com/defenseunicorns/uds-security-hub/pull/319
